Repository tictactrip/luminator, pull requests merged in 2020-01, with the labels that each got.

#9 feat(typing): packages updated + types exported
  package.json
  tsconfig.json
  yarn.lock
Labels: enhancement

#11 fix: http proxy agent package
  package.json
Labels: dependencies

#13 docs: readme [skip ci]
  README.md
Labels: documentation

#14 feat: add custom response type
  src/index.ts
  src/luminator.ts
Labels: enhancement

#16 feat: create LuminatorError class
  __tests__/unit/index.ts
  src/index.ts
  src/luminator.ts
Labels: enhancement
